version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: TheSaviourEking/nginx
    container_name: my_custom_nginx
    ports:
      - "80:80"
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
    name: my_custom_network
